apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: momentum-server-hpa
  namespace: mom-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: momentum-server-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Target 50% CPU utilization
